name: Build Docs

on:
  push:
    paths:
    - "**.py"
    - "**.rst"
    - "**.html"
    - "**.css"
    - ".github/workflows/docs.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r .github/docs/requirements.txt
          pip install jsbeautifier

      - name: Build documentation
        run: |
          cd .github/docs
          make html
          find . -name "*.js" -not -path "./.git/*" -exec js-beautify --indent-size 2 -o {} {} \;
          find . -name "*.css" -not -path "./.git/*" -exec js-beautify --indent-size 2 -o {} {} \;



      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .github/docs/build/html
         # single-commit: true
          git-config-name: "github-actions[bot]"
          git-config-email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit-message: "Deploy to gh-pages"

      - name: Delete old workflow run
        uses: Viyomx/delete-workflow-runs@v1.0.1