name: Replace
on:
  push:
    paths:
      - ".github/workflows/replace.yml"
jobs:
  replace-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace text
        shell: bash
        run: |
          declare -A replacements=(
            ["call_1"]="BOT_ADMIN_REQUIRED"
            ["call_2"]="ASSISTANT_BANNED"
            ["call_3"]="ASSISTANT_INVITE_EXCEPTION"
            ["call_4"]="INVITE_PERMISSION_REQUIRED"
            ["call_5"]="ASSISTANT_JOINING_WAIT"
            ["call_6"]="ASSISTANT_JOIN_SUCCESS"
            ["call_7"]="STREAM_SWITCH_FAILED"
            ["call_8"]="DOWNLOADING_NEXT_TRACK"
            ["call_9"]="ASSISTANT_TOO_MANY_CHATS"
            ["call_10"]="ASSISTANT_FLOOD_WAIT"
          )


          for key in "${!replacements[@]}"; do
            find . -type d \( -name ".git" -o -path "./.github/*" \) -prune -o \
            \( -type f \( -name "*.py" -o -name "*.yml" \) \) \
            -exec sed -i "s/\b$key\b/${replacements[$key]}/g" {} +
          done

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Replace text in Python files"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Delete old workflow run
        uses: Viyomx/delete-workflow-runs@dev
