name: Replace
on:
  push:
    paths:
      - ".github/workflows/replace.yml"
jobs:
  replace-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace
        shell: bash
        run: |
          declare -A replacements=(
            ["Active"]="ACTIVE_HELPER"
            ["Admin"]="ADMIN_HELPER"
            ["Auth"]="AUTH_HELPER"
            ["Blist"]="BLIST_HELPER"
            ["Bot"]="BOT_HELPER"
            ["Dev"]="DEV_HELPER"
            ["Gcast"]="GCAST_HELPER"
            ["PList"]="PLIST_HELPER"
            ["Play"]="PLAY_HELPER"
          )

          for key in "${!replacements[@]}"; do
            find . -type d \( -name ".git" -o -path "./.github/*" \) -prune -o \
            -type f -name "*.yml" \
            -exec sed -i -E "s/^(\s*)$key(\s*:) /\1${replacements[$key]}\2 /g" {} +
          done

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Replace"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Delete old workflow run
        uses: Viyomx/delete-workflow-runs@dev
