name: Replace
on:
  push:
    paths:
      - ".github/workflows/replace.yml"
jobs:
  replace-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace text
        run: |
         declare -A replacements=(
           ["general_4"]="ANONYMOUS_ADMIN"
           ["general_5"]="PERMISSION_REQUIRED"
           ["general_6"]="NO_ACTIVE_VIDEO_STREAM"
           ["general_1"]="USER_IDENTIFIER_REQUIRED"
           ["general_2"]="COMMAND_USAGE_ERROR"
         )

         find . -type d \( -name ".git" -o -path "./.github/*" \) -prune -o \
         \( -type f \( -name "*.py" -o -name "*.yml" \) \) \
         -exec sed -i $(printf ' -e "s/\\b%s\\b/%s/g"' "${!replacements[@]}" "${replacements[@]}") {} +

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Replace text in Python files"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Delete old workflow run
        uses: Viyomx/delete-workflow-runs@dev
